1- Introduction to Numpy

In [1]:
# import numpy as np
import numpy as np

In [3]:
# Create two new lists weight and height
person_height = [5.2, 5.4, 5.6,5.7,6]
person_weight = [70,60,65,76,75]

# Create two numpy array from weight and height
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [6]:
# print person_height and person_weight arrays
person_height


array([5.2, 5.4, 5.6, 5.7, 6. ])

In [7]:
person_weight

array([70, 60, 65, 76, 75])

In [8]:
# print type of person height
print(type(person_height))

<class 'numpy.ndarray'>


2- Indexing an array

Indexing in 1_dimension

In [9]:
# creating an array
my_array = np.array([72,75,87,76,56])
print(my_array)

[72 75 87 76 56]


Each element in the array can be  accessed by passing the positional index of the element

In [10]:
# get the first element
# index starts from 0
print(my_array[0])
# get the 3rd element
print(my_array[2])

72
87


Indexing in 2_dimension

In [11]:
my_array = np.array([[12,13,14],
                    [17,18,19],
                    [23,26,21]])
my_array

array([[12, 13, 14],
       [17, 18, 19],
       [23, 26, 21]])

We can retrieve an element of 2D array by using two indices i and j , i select rows and j select columns

In [12]:
# Get the element in 3rd row and 2nd column
print(my_array[2,1])

26


In [13]:
# we can also pass ith row and jth column in separate brackets
print(my_array[2][1])

26


picking a row and column

we can also select a single row and single column

In [14]:
# select 3rd row 
print(my_array[2])

[23 26 21]


In [15]:
#  select 2nd column
print(my_array[:, 1])

[13 18 26]


3- Slicing an array

Slicing 1D array

In [17]:
my_array = [12,35,15,17,81]

In [19]:
# pick the 2nd, 3rd and 4th ement from the array
new_array = my_array[1:4]
new_array

[35, 15, 17]

Slicing notation specifies starts and end value [start:end] where start is inclusive but end is exclusive

In [21]:
# first three elements
d = my_array[:3]
d

[12, 35, 15]

In [23]:
# all the elements from 15
c = my_array[2:]
c

[15, 17, 81]

In [24]:
# get the entire array
e = my_array[:]
e

[12, 35, 15, 17, 81]

Slicing 2D array

In [25]:
my_array = np.array([[1,2,3,4,5],
            [26,17,76,86,78],
            [25,30,31,31,32],
            [98,99,97,96,94]])
my_array

array([[ 1,  2,  3,  4,  5],
       [26, 17, 76, 86, 78],
       [25, 30, 31, 31, 32],
       [98, 99, 97, 96, 94]])

In [26]:
# select all rows except 1st
# select 2nd and 3rd columns
print(my_array[1:, 2:4])

[[76 86]
 [31 31]
 [97 96]]


Note: Index returns an element of array, while slice returns a list of elements

4- Operations on Array

In [27]:
my_array1 = np.array([120,123,124,145,176])
my_array2 = np.arange(5)

Add the two arrays

In [28]:
my_array3 = my_array1 + my_array2
my_array3

array([120, 124, 126, 148, 180])

If you try to add two arrays with same dimensions but different elements you get an error

In [29]:
# Multiply each element in array by 4
my_array1 * 4

array([480, 492, 496, 580, 704])

In [31]:
## use '**' to compute power of each element
my_array1 ** 2

array([14400, 15129, 15376, 21025, 30976], dtype=int32)

Using Numpy with Comparison Expressions

In [32]:
my_array = np.array([34,43,45,76,32])
# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True,  True, False])

pass the above boolean array to the main array to fetch the values that satisfy the comparison condition

In [33]:
# elements greater than or equal to 40
my_array[new_array]

array([43, 45, 76])

In [34]:
my_array[my_array >= 40]

array([43, 45, 76])

5- Arithmetic functions in Numpy

In [35]:
my_array = np.array([1,5,6,7,9])
my_array

array([1, 5, 6, 7, 9])

sum():

sum function add all  values in the array and gives a scalar output

In [36]:
np.sum(my_array)

28

In [37]:
# add all the elements of my array
my_array.sum()

28

min(): 

min function finds the lowest value in the array

In [38]:
# find minimum of my_array
my_array.min()

1

power():
    
power function raises the number in array to given value

In [39]:
# get the cube of elements of my_array
np.power(my_array, 3)

array([  1, 125, 216, 343, 729], dtype=int32)

In [40]:
my_array ** 3

array([  1, 125, 216, 343, 729], dtype=int32)

6- Concatenate the arrays 

Concatenate 1D arrays

In [42]:
# Concatenate two 1D arrays
array_x = np.array([12,13,14])
array_y = np.array([21,22,23])
np.concatenate([array_x, array_y])

array([12, 13, 14, 21, 22, 23])

In [43]:
# you can also concatenate more than 2 arrays at once
array_z = np.array([43,56])
print(np.concatenate([array_x, array_y, array_z]))

[12 13 14 21 22 23 43 56]


Concatenate 2D array

In [44]:
# Create a 2D array
my_array = np.array([[1,2,3],
                    [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
## Concatenate along the first axis
# by default concatenate is along 'axis = 0'
np.concatenate([my_array,my_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
## Concatenate along the 2nd axis
np.concatenate([my_array, my_array], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Concatenate 1D and 2D array

Note: you can not concatenate two arrays of different dimensions

7- Splitting of array

splitting is used to split the arrays into multiple sub_arrays. It is opposite to concatenation, which is implemented
by the functions split(), hsplit() and so on

split():

In [47]:
# split the array into sub_arrays 
array_x = np.arange(8)
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [48]:
## Split the 1D array at indicated positions 
# split occurs at 6th and 7th indices

array_y = np.split(array_x,[5,7])
array_y

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]

split array_x into 3 equal arrays 

split() function does not allow integer(N) as the number of splits, if N does not divide the array into sub_arrays of equal length

array_split(): It is used to split the arrays into sub_arrays. It takes the integer 'N' as the input of number of splits,even if 'N' does not divide the array into sub_arrays of equal length

In [49]:
# split array_x into 3 sub_arrays using array_split
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

We split an array of length 8 into 3 sub_arrays, the function array_split() returns 8 % 3(=2) sub_arrays of size 8/3 + 1(=3) and the rest one sub_array of size 8/3(=2)

vsplit():

The vsplit() is used to split an array into ,multiple sub_arrays vertically(row_wise)

In [50]:
my_array = np.arange(20).reshape(4,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
np.vsplit(my_array,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

hsplit():

The hsplit() function used to split an array  into mulptipe sub_arrays horizontally(column_wise)

In [52]:
my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [53]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]